export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST';
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
export const PROJECT_CREATE_FAIL = 'PROJECT_CREATE_FAIL';

// delete project
export const PROJECT_DELETE_REQUEST = 'PROJECT_DELETE_REQUEST';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';
export const PROJECT_DELETE_FAIL = 'PROJECT_DELETE_FAIL';

// update project
export const PROJECT_UPDATE_REQUEST = 'PROJECT_UPDATE_REQUEST';
export const PROJECT_UPDATE_SUCCESS = 'PROJECT_UPDATE_SUCCESS';
export const PROJECT_UPDATE_FAIL = 'PROJECT_UPDATE_FAIL';
export const PROJECT_UPDATE_RESET = 'PROJECT_UPDATE_RESET';

// project list 
export const PROJECT_LIST_REQUEST = 'PROJECT_LIST_REQUEST';
// workspace create 
export const WORKSPACE_CREATE_REQUEST = 'WORKSPACE_CREATE_REQUEST';
export const WORKSPACE_CREATE_SUCCESS = 'WORKSPACE_CREATE_SUCCESS';
export const WORKSPACE_CREATE_FAIL = 'WORKSPACE_CREATE_FAIL';

// workspace update
export const WORKSPACE_UPDATE_REQUEST = 'WORKSPACE_UPDATE_REQUEST';
export const WORKSPACE_UPDATE_SUCCESS = 'WORKSPACE_UPDATE_SUCCESS';
export const WORKSPACE_UPDATE_FAIL = 'WORKSPACE_UPDATE_FAIL';

// Workspace delete
export const WORKSPACE_DELETE_REQUEST = 'WORKSPACE_DELETE_REQUEST';
export const WORKSPACE_DELETE_SUCCESS = 'WORKSPACE_DELETE_SUCCESS';
export const WORKSPACE_DELETE_FAIL = 'WORKSPACE_DELETE_FAIL';

// workspace List
export const WORKSPACE_LIST_REQUEST = 'WORKSPACE_LIST_REQUEST';
export const WORKSPACE_LIST_SUCCESS = 'WORKSPACE_LIST_SUCCESS';
export const WORKSPACE_LIST_FAIL = 'WORKSPACE_LIST_FAIL';